# -*- coding: utf-8 -*-
"""HeartDiseaseClasification

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i-R7e8WzUhW78aOOxkfx1QocQKQX-sDY
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

# Mount the drive
# import Google drive
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

#!ls /content/drive/MyDrive/ColabNotebooks/datas/Dry_Bean_Dataset.xlsx
file_path = '/content/drive/MyDrive/ColabNotebooks/datas/heart.csv'

data = pd.read_csv(file_path)

data.head()

data.info()

data.columns

data.shape

data.describe().T

data.isnull().sum()

data.isna().sum()

data = data.drop_duplicates()

x = data.drop("target", axis=1)
y = data["target"]

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = 42)

standardscaler = StandardScaler()
x_train  = standardscaler.fit_transform(X_train)
x_test = standardscaler.fit_transform(X_test)

# KNN
dtc_classifier = DecisionTreeClassifier()
dtc_classifier.fit(x_train, y_train)
y_predict = dtc_classifier.predict(x_test)
y_predict

"""# Nowa sekcja"""

acc = accuracy_score(y_test, y_predict)
print(acc)

from sklearn.metrics import classification_report,accuracy_score

print(classification_report(y_test,y_predict))